/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace IMarketplace {
  export type MintedTokenInfoStruct = {
    tokenId: PromiseOrValue<BigNumberish>;
    mintedTokenPrice: PromiseOrValue<BigNumberish>;
    tokenURI: PromiseOrValue<string>;
  };

  export type MintedTokenInfoStructOutput = [BigNumber, BigNumber, string] & {
    tokenId: BigNumber;
    mintedTokenPrice: BigNumber;
    tokenURI: string;
  };

  export type TokenParamsStruct = {
    pricePerOneToken: PromiseOrValue<BigNumberish>;
    minNFTFloorPrice: PromiseOrValue<BigNumberish>;
    voucherTokensAmount: PromiseOrValue<BigNumberish>;
    isNFTBuyable: PromiseOrValue<boolean>;
    voucherTokenContract: PromiseOrValue<string>;
    fundsRecipient: PromiseOrValue<string>;
  };

  export type TokenParamsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    string,
    string
  ] & {
    pricePerOneToken: BigNumber;
    minNFTFloorPrice: BigNumber;
    voucherTokensAmount: BigNumber;
    isNFTBuyable: boolean;
    voucherTokenContract: string;
    fundsRecipient: string;
  };
}

export interface MarketPlaceInterface extends utils.Interface {
  functions: {
    "__Marketplace_init(string)": FunctionFragment;
    "addToken(string,string,(uint256,uint256,uint256,bool,address,address))": FunctionFragment;
    "baseTokenContractsURI()": FunctionFragment;
    "buyToken(address,uint256,address,uint256,uint256,uint256,string,bytes32,bytes32,uint8)": FunctionFragment;
    "buyTokenByNFT(address,uint256,address,uint256,uint256,uint256,string,bytes32,bytes32,uint8)": FunctionFragment;
    "getInjector()": FunctionFragment;
    "getTokenContractsCount()": FunctionFragment;
    "getTokenContractsPart(uint256,uint256)": FunctionFragment;
    "getTokenParams(address)": FunctionFragment;
    "getUserTokenIDs(address,address)": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "setBaseTokenContractsURI(string)": FunctionFragment;
    "setDependencies(address,bytes)": FunctionFragment;
    "setInjector(address)": FunctionFragment;
    "updateAllParams(address,string,string,(uint256,uint256,uint256,bool,address,address))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "__Marketplace_init"
      | "addToken"
      | "baseTokenContractsURI"
      | "buyToken"
      | "buyTokenByNFT"
      | "getInjector"
      | "getTokenContractsCount"
      | "getTokenContractsPart"
      | "getTokenParams"
      | "getUserTokenIDs"
      | "onERC721Received"
      | "setBaseTokenContractsURI"
      | "setDependencies"
      | "setInjector"
      | "updateAllParams"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "__Marketplace_init",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      IMarketplace.TokenParamsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "baseTokenContractsURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokenByNFT",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getInjector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenContractsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenContractsPart",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenParams",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokenIDs",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseTokenContractsURI",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDependencies",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setInjector",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAllParams",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      IMarketplace.TokenParamsStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "__Marketplace_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseTokenContractsURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyTokenByNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInjector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenContractsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenContractsPart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokenIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseTokenContractsURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInjector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAllParams",
    data: BytesLike
  ): Result;

  events: {
    "BaseTokenContractsURIUpdated(string)": EventFragment;
    "PaidTokensWithdrawn(address,address,address,uint256)": EventFragment;
    "SuccessfullyMinted(address,address,tuple,address,uint256,uint256,uint256,address)": EventFragment;
    "SuccessfullyMintedByNFT(address,address,tuple,address,uint256,uint256,address)": EventFragment;
    "TokenContractDeployed(address,string,string,tuple)": EventFragment;
    "TokenContractParamsUpdated(address,string,string,tuple)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "BaseTokenContractsURIUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaidTokensWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SuccessfullyMinted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SuccessfullyMintedByNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenContractDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenContractParamsUpdated"): EventFragment;
}

export interface BaseTokenContractsURIUpdatedEventObject {
  newBaseTokenContractsURI: string;
}
export type BaseTokenContractsURIUpdatedEvent = TypedEvent<
  [string],
  BaseTokenContractsURIUpdatedEventObject
>;

export type BaseTokenContractsURIUpdatedEventFilter =
  TypedEventFilter<BaseTokenContractsURIUpdatedEvent>;

export interface PaidTokensWithdrawnEventObject {
  tokenContract: string;
  tokenAddr: string;
  recipient: string;
  amount: BigNumber;
}
export type PaidTokensWithdrawnEvent = TypedEvent<
  [string, string, string, BigNumber],
  PaidTokensWithdrawnEventObject
>;

export type PaidTokensWithdrawnEventFilter =
  TypedEventFilter<PaidTokensWithdrawnEvent>;

export interface SuccessfullyMintedEventObject {
  tokenContract: string;
  recipient: string;
  mintedTokenInfo: IMarketplace.MintedTokenInfoStructOutput;
  paymentTokenAddress: string;
  paidTokensAmount: BigNumber;
  paymentTokenPrice: BigNumber;
  discount: BigNumber;
  fundsRecipient: string;
}
export type SuccessfullyMintedEvent = TypedEvent<
  [
    string,
    string,
    IMarketplace.MintedTokenInfoStructOutput,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ],
  SuccessfullyMintedEventObject
>;

export type SuccessfullyMintedEventFilter =
  TypedEventFilter<SuccessfullyMintedEvent>;

export interface SuccessfullyMintedByNFTEventObject {
  tokenContract: string;
  recipient: string;
  mintedTokenInfo: IMarketplace.MintedTokenInfoStructOutput;
  nftAddress: string;
  tokenId: BigNumber;
  nftFloorPrice: BigNumber;
  fundsRecipient: string;
}
export type SuccessfullyMintedByNFTEvent = TypedEvent<
  [
    string,
    string,
    IMarketplace.MintedTokenInfoStructOutput,
    string,
    BigNumber,
    BigNumber,
    string
  ],
  SuccessfullyMintedByNFTEventObject
>;

export type SuccessfullyMintedByNFTEventFilter =
  TypedEventFilter<SuccessfullyMintedByNFTEvent>;

export interface TokenContractDeployedEventObject {
  tokenContract: string;
  tokenName: string;
  tokenSymbol: string;
  tokenParams: IMarketplace.TokenParamsStructOutput;
}
export type TokenContractDeployedEvent = TypedEvent<
  [string, string, string, IMarketplace.TokenParamsStructOutput],
  TokenContractDeployedEventObject
>;

export type TokenContractDeployedEventFilter =
  TypedEventFilter<TokenContractDeployedEvent>;

export interface TokenContractParamsUpdatedEventObject {
  tokenContract: string;
  tokenName: string;
  tokenSymbol: string;
  tokenParams: IMarketplace.TokenParamsStructOutput;
}
export type TokenContractParamsUpdatedEvent = TypedEvent<
  [string, string, string, IMarketplace.TokenParamsStructOutput],
  TokenContractParamsUpdatedEventObject
>;

export type TokenContractParamsUpdatedEventFilter =
  TypedEventFilter<TokenContractParamsUpdatedEvent>;

export interface MarketPlace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketPlaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __Marketplace_init(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      tokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    baseTokenContractsURI(overrides?: CallOverrides): Promise<[string]>;

    buyToken(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      paymentTokenAddress_: PromiseOrValue<string>,
      paymentTokenPrice_: PromiseOrValue<BigNumberish>,
      discount_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyTokenByNFT(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      nftAddress_: PromiseOrValue<string>,
      nftFloorPrice_: PromiseOrValue<BigNumberish>,
      tokenId_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getInjector(
      overrides?: CallOverrides
    ): Promise<[string] & { injector_: string }>;

    getTokenContractsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTokenContractsPart(
      offset_: PromiseOrValue<BigNumberish>,
      limit_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getTokenParams(
      tokenContract_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[IMarketplace.TokenParamsStructOutput]>;

    getUserTokenIDs(
      tokenContract_: PromiseOrValue<string>,
      userAddr_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { tokenIDs_: BigNumber[] }>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBaseTokenContractsURI(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDependencies(
      contractsRegistry_: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setInjector(
      injector_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAllParams(
      tokenContract_: PromiseOrValue<string>,
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      newTokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  __Marketplace_init(
    baseTokenContractsURI_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addToken(
    name_: PromiseOrValue<string>,
    symbol_: PromiseOrValue<string>,
    tokenParams_: IMarketplace.TokenParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  baseTokenContractsURI(overrides?: CallOverrides): Promise<string>;

  buyToken(
    tokenContract_: PromiseOrValue<string>,
    futureTokenId_: PromiseOrValue<BigNumberish>,
    paymentTokenAddress_: PromiseOrValue<string>,
    paymentTokenPrice_: PromiseOrValue<BigNumberish>,
    discount_: PromiseOrValue<BigNumberish>,
    endTimestamp_: PromiseOrValue<BigNumberish>,
    tokenURI_: PromiseOrValue<string>,
    r_: PromiseOrValue<BytesLike>,
    s_: PromiseOrValue<BytesLike>,
    v_: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyTokenByNFT(
    tokenContract_: PromiseOrValue<string>,
    futureTokenId_: PromiseOrValue<BigNumberish>,
    nftAddress_: PromiseOrValue<string>,
    nftFloorPrice_: PromiseOrValue<BigNumberish>,
    tokenId_: PromiseOrValue<BigNumberish>,
    endTimestamp_: PromiseOrValue<BigNumberish>,
    tokenURI_: PromiseOrValue<string>,
    r_: PromiseOrValue<BytesLike>,
    s_: PromiseOrValue<BytesLike>,
    v_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getInjector(overrides?: CallOverrides): Promise<string>;

  getTokenContractsCount(overrides?: CallOverrides): Promise<BigNumber>;

  getTokenContractsPart(
    offset_: PromiseOrValue<BigNumberish>,
    limit_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTokenParams(
    tokenContract_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IMarketplace.TokenParamsStructOutput>;

  getUserTokenIDs(
    tokenContract_: PromiseOrValue<string>,
    userAddr_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBaseTokenContractsURI(
    baseTokenContractsURI_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDependencies(
    contractsRegistry_: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setInjector(
    injector_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAllParams(
    tokenContract_: PromiseOrValue<string>,
    name_: PromiseOrValue<string>,
    symbol_: PromiseOrValue<string>,
    newTokenParams_: IMarketplace.TokenParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    __Marketplace_init(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      tokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    baseTokenContractsURI(overrides?: CallOverrides): Promise<string>;

    buyToken(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      paymentTokenAddress_: PromiseOrValue<string>,
      paymentTokenPrice_: PromiseOrValue<BigNumberish>,
      discount_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyTokenByNFT(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      nftAddress_: PromiseOrValue<string>,
      nftFloorPrice_: PromiseOrValue<BigNumberish>,
      tokenId_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getInjector(overrides?: CallOverrides): Promise<string>;

    getTokenContractsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenContractsPart(
      offset_: PromiseOrValue<BigNumberish>,
      limit_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTokenParams(
      tokenContract_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IMarketplace.TokenParamsStructOutput>;

    getUserTokenIDs(
      tokenContract_: PromiseOrValue<string>,
      userAddr_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    setBaseTokenContractsURI(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDependencies(
      contractsRegistry_: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setInjector(
      injector_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAllParams(
      tokenContract_: PromiseOrValue<string>,
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      newTokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BaseTokenContractsURIUpdated(string)"(
      newBaseTokenContractsURI?: null
    ): BaseTokenContractsURIUpdatedEventFilter;
    BaseTokenContractsURIUpdated(
      newBaseTokenContractsURI?: null
    ): BaseTokenContractsURIUpdatedEventFilter;

    "PaidTokensWithdrawn(address,address,address,uint256)"(
      tokenContract?: PromiseOrValue<string> | null,
      tokenAddr?: PromiseOrValue<string> | null,
      recipient?: null,
      amount?: null
    ): PaidTokensWithdrawnEventFilter;
    PaidTokensWithdrawn(
      tokenContract?: PromiseOrValue<string> | null,
      tokenAddr?: PromiseOrValue<string> | null,
      recipient?: null,
      amount?: null
    ): PaidTokensWithdrawnEventFilter;

    "SuccessfullyMinted(address,address,tuple,address,uint256,uint256,uint256,address)"(
      tokenContract?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      mintedTokenInfo?: null,
      paymentTokenAddress?: PromiseOrValue<string> | null,
      paidTokensAmount?: null,
      paymentTokenPrice?: null,
      discount?: null,
      fundsRecipient?: null
    ): SuccessfullyMintedEventFilter;
    SuccessfullyMinted(
      tokenContract?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      mintedTokenInfo?: null,
      paymentTokenAddress?: PromiseOrValue<string> | null,
      paidTokensAmount?: null,
      paymentTokenPrice?: null,
      discount?: null,
      fundsRecipient?: null
    ): SuccessfullyMintedEventFilter;

    "SuccessfullyMintedByNFT(address,address,tuple,address,uint256,uint256,address)"(
      tokenContract?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      mintedTokenInfo?: null,
      nftAddress?: PromiseOrValue<string> | null,
      tokenId?: null,
      nftFloorPrice?: null,
      fundsRecipient?: null
    ): SuccessfullyMintedByNFTEventFilter;
    SuccessfullyMintedByNFT(
      tokenContract?: PromiseOrValue<string> | null,
      recipient?: PromiseOrValue<string> | null,
      mintedTokenInfo?: null,
      nftAddress?: PromiseOrValue<string> | null,
      tokenId?: null,
      nftFloorPrice?: null,
      fundsRecipient?: null
    ): SuccessfullyMintedByNFTEventFilter;

    "TokenContractDeployed(address,string,string,tuple)"(
      tokenContract?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenParams?: null
    ): TokenContractDeployedEventFilter;
    TokenContractDeployed(
      tokenContract?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenParams?: null
    ): TokenContractDeployedEventFilter;

    "TokenContractParamsUpdated(address,string,string,tuple)"(
      tokenContract?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenParams?: null
    ): TokenContractParamsUpdatedEventFilter;
    TokenContractParamsUpdated(
      tokenContract?: PromiseOrValue<string> | null,
      tokenName?: null,
      tokenSymbol?: null,
      tokenParams?: null
    ): TokenContractParamsUpdatedEventFilter;
  };

  estimateGas: {
    __Marketplace_init(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      tokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    baseTokenContractsURI(overrides?: CallOverrides): Promise<BigNumber>;

    buyToken(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      paymentTokenAddress_: PromiseOrValue<string>,
      paymentTokenPrice_: PromiseOrValue<BigNumberish>,
      discount_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyTokenByNFT(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      nftAddress_: PromiseOrValue<string>,
      nftFloorPrice_: PromiseOrValue<BigNumberish>,
      tokenId_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getInjector(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenContractsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenContractsPart(
      offset_: PromiseOrValue<BigNumberish>,
      limit_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenParams(
      tokenContract_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserTokenIDs(
      tokenContract_: PromiseOrValue<string>,
      userAddr_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBaseTokenContractsURI(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDependencies(
      contractsRegistry_: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setInjector(
      injector_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAllParams(
      tokenContract_: PromiseOrValue<string>,
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      newTokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __Marketplace_init(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addToken(
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      tokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    baseTokenContractsURI(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyToken(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      paymentTokenAddress_: PromiseOrValue<string>,
      paymentTokenPrice_: PromiseOrValue<BigNumberish>,
      discount_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyTokenByNFT(
      tokenContract_: PromiseOrValue<string>,
      futureTokenId_: PromiseOrValue<BigNumberish>,
      nftAddress_: PromiseOrValue<string>,
      nftFloorPrice_: PromiseOrValue<BigNumberish>,
      tokenId_: PromiseOrValue<BigNumberish>,
      endTimestamp_: PromiseOrValue<BigNumberish>,
      tokenURI_: PromiseOrValue<string>,
      r_: PromiseOrValue<BytesLike>,
      s_: PromiseOrValue<BytesLike>,
      v_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getInjector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenContractsCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenContractsPart(
      offset_: PromiseOrValue<BigNumberish>,
      limit_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenParams(
      tokenContract_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUserTokenIDs(
      tokenContract_: PromiseOrValue<string>,
      userAddr_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBaseTokenContractsURI(
      baseTokenContractsURI_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDependencies(
      contractsRegistry_: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setInjector(
      injector_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAllParams(
      tokenContract_: PromiseOrValue<string>,
      name_: PromiseOrValue<string>,
      symbol_: PromiseOrValue<string>,
      newTokenParams_: IMarketplace.TokenParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
