/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { MarketPlace, MarketPlaceInterface } from "../MarketPlace";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "newBaseTokenContractsURI",
        type: "string",
      },
    ],
    name: "BaseTokenContractsURIUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenAddr",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PaidTokensWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "mintedTokenPrice",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "tokenURI",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct IMarketplace.MintedTokenInfo",
        name: "mintedTokenInfo",
        type: "tuple",
      },
      {
        indexed: true,
        internalType: "address",
        name: "paymentTokenAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "paidTokensAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "paymentTokenPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "discount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "fundsRecipient",
        type: "address",
      },
    ],
    name: "SuccessfullyMinted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "mintedTokenPrice",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "tokenURI",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct IMarketplace.MintedTokenInfo",
        name: "mintedTokenInfo",
        type: "tuple",
      },
      {
        indexed: true,
        internalType: "address",
        name: "nftAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nftFloorPrice",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "fundsRecipient",
        type: "address",
      },
    ],
    name: "SuccessfullyMintedByNFT",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "tokenName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "tokenSymbol",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minNFTFloorPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "voucherTokensAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "voucherTokenContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "fundsRecipient",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isNFTBuyable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct IMarketplace.TokenParams",
        name: "tokenParams",
        type: "tuple",
      },
    ],
    name: "TokenContractDeployed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "tokenContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "tokenName",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "tokenSymbol",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minNFTFloorPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "voucherTokensAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "voucherTokenContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "fundsRecipient",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isNFTBuyable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct IMarketplace.TokenParams",
        name: "tokenParams",
        type: "tuple",
      },
    ],
    name: "TokenContractParamsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "baseTokenContractsURI_",
        type: "string",
      },
    ],
    name: "__Marketplace_init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol_",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minNFTFloorPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "voucherTokensAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "voucherTokenContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "fundsRecipient",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isNFTBuyable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
        ],
        internalType: "struct IMarketplace.TokenParams",
        name: "tokenParams_",
        type: "tuple",
      },
    ],
    name: "addToken",
    outputs: [
      {
        internalType: "address",
        name: "tokenProxy_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "baseTokenContractsURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenContract_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "futureTokenId_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "paymentTokenAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "paymentTokenPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "discount_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTimestamp_",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "tokenURI_",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "r_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s_",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "v_",
        type: "uint8",
      },
    ],
    name: "buyToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenContract_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "futureTokenId_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "nftAddress_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "nftFloorPrice_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTimestamp_",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "tokenURI_",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "r_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s_",
        type: "bytes32",
      },
      {
        internalType: "uint8",
        name: "v_",
        type: "uint8",
      },
    ],
    name: "buyTokenByNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveTokenContractsCount",
    outputs: [
      {
        internalType: "uint256",
        name: "count_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tokenContract_",
        type: "address[]",
      },
    ],
    name: "getBaseTokenParams",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenContract",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "tokenName",
            type: "string",
          },
        ],
        internalType: "struct IMarketplace.BaseTokenParams[]",
        name: "baseTokenParams_",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "offset_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit_",
        type: "uint256",
      },
    ],
    name: "getBaseTokenParamsPart",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenContract",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "tokenName",
            type: "string",
          },
        ],
        internalType: "struct IMarketplace.BaseTokenParams[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "tokenContracts_",
        type: "address[]",
      },
    ],
    name: "getDetailedTokenParams",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenContract",
            type: "address",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "pricePerOneToken",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "minNFTFloorPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "voucherTokensAmount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "voucherTokenContract",
                type: "address",
              },
              {
                internalType: "address",
                name: "fundsRecipient",
                type: "address",
              },
              {
                internalType: "bool",
                name: "isNFTBuyable",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "isDisabled",
                type: "bool",
              },
            ],
            internalType: "struct IMarketplace.TokenParams",
            name: "tokenParams",
            type: "tuple",
          },
          {
            internalType: "string",
            name: "tokenName",
            type: "string",
          },
          {
            internalType: "string",
            name: "tokenSymbol",
            type: "string",
          },
        ],
        internalType: "struct IMarketplace.DetailedTokenParams[]",
        name: "detailedTokenParams_",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "offset_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit_",
        type: "uint256",
      },
    ],
    name: "getDetailedTokenParamsPart",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenContract",
            type: "address",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "pricePerOneToken",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "minNFTFloorPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "voucherTokensAmount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "voucherTokenContract",
                type: "address",
              },
              {
                internalType: "address",
                name: "fundsRecipient",
                type: "address",
              },
              {
                internalType: "bool",
                name: "isNFTBuyable",
                type: "bool",
              },
              {
                internalType: "bool",
                name: "isDisabled",
                type: "bool",
              },
            ],
            internalType: "struct IMarketplace.TokenParams",
            name: "tokenParams",
            type: "tuple",
          },
          {
            internalType: "string",
            name: "tokenName",
            type: "string",
          },
          {
            internalType: "string",
            name: "tokenSymbol",
            type: "string",
          },
        ],
        internalType: "struct IMarketplace.DetailedTokenParams[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getInjector",
    outputs: [
      {
        internalType: "address",
        name: "injector_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTokenContractsCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "offset_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit_",
        type: "uint256",
      },
    ],
    name: "getTokenContractsPart",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "userAddr_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "offset_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit_",
        type: "uint256",
      },
    ],
    name: "getUserTokensPart",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "tokenContract",
            type: "address",
          },
          {
            internalType: "uint256[]",
            name: "tokenIds",
            type: "uint256[]",
          },
        ],
        internalType: "struct IMarketplace.UserTokens[]",
        name: "userTokens_",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC721Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "baseTokenContractsURI_",
        type: "string",
      },
    ],
    name: "setBaseTokenContractsURI",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractsRegistry_",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "setDependencies",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "injector_",
        type: "address",
      },
    ],
    name: "setInjector",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenContract_",
        type: "address",
      },
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol_",
        type: "string",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "pricePerOneToken",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minNFTFloorPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "voucherTokensAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "voucherTokenContract",
            type: "address",
          },
          {
            internalType: "address",
            name: "fundsRecipient",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isNFTBuyable",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDisabled",
            type: "bool",
          },
        ],
        internalType: "struct IMarketplace.TokenParams",
        name: "newTokenParams_",
        type: "tuple",
      },
    ],
    name: "updateAllParams",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddr_",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient_",
        type: "address",
      },
    ],
    name: "withdrawCurrency",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MarketPlace__factory {
  static readonly abi = _abi;
  static createInterface(): MarketPlaceInterface {
    return new utils.Interface(_abi) as MarketPlaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarketPlace {
    return new Contract(address, _abi, signerOrProvider) as MarketPlace;
  }
}
