export { default as PromocodeForm } from '@/forms/PromocodeForm.vue'
export { default as NftForm } from '@/forms/NftForm.vue'
export { default as LoginForm } from '@/forms/LoginForm.vue'
export { default as CreateVoucherForm } from '@/forms/CreateVoucherForm.vue'
export { default as WithdrawForm } from '@/forms/WithdrawForm.vue'
